spring.application.name=employee-service
spring.profiles.active=local

#logging configuration
logging.file.name=logs/employee-service.log
# Roll the log file over to a new one once it hits 10 Megabytes
#logging.logback.rollingpolicy.max-file-size=10MB

# Keep up to 7 days worth of history before deleting old logs
#logging.logback.rollingpolicy.max-history=7

# Total size cap for all log files combined
#logging.logback.rollingpolicy.total-size-cap=1GB